CREATE TABLE IF NOT EXISTS `attendance_records` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_number` VARCHAR(64) NOT NULL,
  `academic_year_id` INT UNSIGNED NOT NULL,
  `study_period_id` INT UNSIGNED NOT NULL,
  `attendance_date` DATE NOT NULL,
  `class_id` INT UNSIGNED NOT NULL,
  `stream_id` INT UNSIGNED DEFAULT NULL,
  `student_id` INT UNSIGNED NOT NULL,
  `status` ENUM('present','absent','late','half_day','excused') NOT NULL DEFAULT 'present',
  `remarks` VARCHAR(500) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by_user_id` INT UNSIGNED DEFAULT NULL,
  `updated_by_user_id` INT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `att_unique_student_day_class` (`school_number`,`student_id`,`class_id`,`academic_year_id`,`study_period_id`,`attendance_date`),
  KEY `att_school_date` (`school_number`,`attendance_date`),
  KEY `att_class_date` (`school_number`,`class_id`,`attendance_date`),
  KEY `att_student_period` (`school_number`,`student_id`,`academic_year_id`,`study_period_id`),
  CONSTRAINT `att_year_fk` FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `att_period_fk` FOREIGN KEY (`study_period_id`) REFERENCES `study_periods` (`id`) ON DELETE CASCADE,
  CONSTRAINT `att_class_fk` FOREIGN KEY (`class_id`) REFERENCES `classes` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `att_student_fk` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE CASCADE,
  CONSTRAINT `att_stream_fk` FOREIGN KEY (`stream_id`) REFERENCES `streams` (`id`) ON DELETE SET NULL,
  CONSTRAINT `att_created_user_fk` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `att_updated_user_fk` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
