/**
 * Permission keys used for role-based access.
 * Each key can be granted per role; '*' means all permissions.
 */
export const PERMISSION_KEYS = [
  { key: 'budget.view', label: 'View budget' },
  { key: 'budget.add', label: 'Add budget (categories & items)' },
  { key: 'budget.edit', label: 'Edit budget' },
  { key: 'budget.delete', label: 'Delete budget' },
  { key: 'contributions.view', label: 'View contributions' },
  { key: 'contributions.add', label: 'Add contributions' },
  { key: 'contributions.edit', label: 'Edit contributions' },
  { key: 'contributions.delete', label: 'Delete contributions' },
  { key: 'expenditures.view', label: 'View expenditures' },
  { key: 'expenditures.add', label: 'Add expenditures' },
  { key: 'expenditures.edit', label: 'Edit expenditures' },
  { key: 'expenditures.delete', label: 'Delete expenditures' },
  { key: 'pledges.view', label: 'View pledges' },
  { key: 'pledges.add', label: 'Add pledges' },
  { key: 'pledges.edit', label: 'Edit pledges' },
  { key: 'pledges.delete', label: 'Delete pledges' },
  { key: 'members.view', label: 'View members' },
  { key: 'members.add', label: 'Add members' },
  { key: 'members.edit', label: 'Edit members' },
  { key: 'members.delete', label: 'Delete members' },
  { key: 'group_categories.view', label: 'View group categories' },
  { key: 'group_categories.add', label: 'Add group categories' },
  { key: 'group_categories.edit', label: 'Edit group categories' },
  { key: 'group_categories.delete', label: 'Delete group categories' },
  { key: 'roles.view', label: 'View roles' },
  { key: 'roles.add', label: 'Add roles' },
  { key: 'roles.edit', label: 'Edit roles' },
  { key: 'roles.delete', label: 'Delete roles' },
  { key: 'committee.view', label: 'View committee' },
  { key: 'committee.assign', label: 'Assign roles to members' },
  { key: 'committee.unassign', label: 'Unassign roles' },
  { key: 'guests.view', label: 'View invited guests' },
  { key: 'guests.add', label: 'Add guests' },
  { key: 'guests.edit', label: 'Edit guests' },
  { key: 'guests.delete', label: 'Delete guests' },
  { key: 'meetings.view', label: 'View meetings' },
  { key: 'meeting_minutes.view', label: 'View meeting minutes' },
  { key: 'meeting_minutes.add', label: 'Add meeting minutes' },
  { key: 'meeting_minutes.edit', label: 'Edit meeting minutes' },
  { key: 'meeting_minutes.delete', label: 'Delete meeting minutes' },
  { key: 'wedding_program.view', label: 'View wedding program' },
  { key: 'wedding_program.add', label: 'Add wedding program items' },
  { key: 'wedding_program.edit', label: 'Edit wedding program' },
  { key: 'wedding_program.delete', label: 'Delete wedding program items' },
  { key: 'vendors.view', label: 'View vendors' },
  { key: 'vendors.add', label: 'Add vendors' },
  { key: 'vendors.edit', label: 'Edit vendors' },
  { key: 'vendors.delete', label: 'Delete vendors' },
  { key: 'vendor_contracts.view', label: 'View vendor contracts' },
  { key: 'vendor_contracts.add', label: 'Add vendor contracts' },
  { key: 'vendor_contracts.edit', label: 'Edit vendor contracts' },
  { key: 'vendor_contracts.delete', label: 'Delete vendor contracts' },
  { key: 'reports.view', label: 'View reports' },
  { key: 'settings.view', label: 'View settings' },
  { key: 'settings.edit', label: 'Edit settings' },
  { key: 'notifications.send', label: 'Send email notifications' }
]

/** Route path -> minimum permission to show in sidebar. null = show to all authenticated users. */
export const ROUTE_PERMISSIONS = {
  '/': null,
  '/budget': 'budget.view',
  '/expenditures': 'expenditures.view',
  '/contributions': 'contributions.view',
  '/pledges': 'pledges.view',
  '/members': 'members.view',
  '/group-category': 'group_categories.view',
  '/roles': 'roles.view',
  '/committee': 'committee.view',
  '/guests': 'guests.view',
  '/meetings': 'meetings.view',
  '/meeting-minutes': 'meeting_minutes.view',
  '/wedding-program': 'wedding_program.view',
  '/vendors': 'vendors.view',
  '/vendor-contracts': 'vendor_contracts.view',
  '/reports/financial': 'reports.view',
  '/reports/contributions': 'reports.view',
  '/reports/guests': 'reports.view',
  '/settings/profile': null,
  '/settings/account': null,
  '/settings/email': 'settings.view',
  '/settings/system': 'settings.view',
  '/email-notifications': 'notifications.send'
}
