/**
 * Route path → permission key. null = any authenticated user.
 */
export const ROUTE_PERMISSIONS = {
  '/dashboard': null,
  '/students': null,
  '/students/admissions': null,
  '/admissions/applicants': null,
  '/admissions/enrollments': null,
  '/students/admissions/board': null,
  '/academics/erp-setup': null,
  '/academics/classes': null,
  '/academics/subjects': null,
  '/academics/teachers': null,
  '/examinations/exam-types': null,
  '/examinations/exam-schedules': null,
  '/examinations/exams': null,
  '/examinations/marks-entry': null,
  '/examinations/score-sheet': null,
  '/examinations/results': null,
  '/finance/dashboard': null,
  '/finance/student-fees': null,
  '/finance/fee-structure': null,
  '/finance/invoices': null,
  '/finance/payments': null,
  '/attendance': null,
  '/attendance/school-general': null,
  '/hr-payroll': null,
  '/hr-payroll/staff': null,
  '/hr-payroll/none-staff': null,
  '/hr-payroll/teachers': null,
  '/hr-payroll/work-attendance': null,
  '/hr-payroll/payroll': null,
  '/hr-payroll/leave-management': null,
  '/reports': null,
  '/communication': null,
  '/settings': null,
  '/portal/dashboard': null,
  '/portal/finance/prn': null,
  '/portal/fees': null,
  '/portal/finance/requirements': null,
  '/portal/finance/structure': null,
  '/portal/finance/invoices': null,
  '/portal/finance/payment-plan': null,
  '/portal/admissions/apply': null,
  '/portal/admissions/history': null,
  '/portal/admissions/enrollment-history': null,
  '/portal/results/provisional': null,
  '/portal/results': null,
  '/portal/timetable': null,
  '/portal/exam-permit': null,
  '/portal/meal-card': null,
  '/portal/canteen/expenditure': null,
  '/portal/canteen/account': null,
  '/portal/bio-data': null,
  '/portal/notifications': null,
  '/portal/calendar': null,
  '/portal/attendance': null,
  '/portal/discipline': null,
  '/portal/password': null,
  '/parent/dashboard': null,
  '/parent/children': null,
  '/parent/results': null,
  '/parent/attendance': null,
  '/parent/fees': null,
  '/parent/timetable': null,
  '/parent/messages': null
}

export const PERMISSION_KEYS = [
  { key: 'students.view', label: 'View students' },
  { key: 'finance.view', label: 'View finance' },
  { key: 'exams.view', label: 'View exams' },
  { key: 'attendance.view', label: 'View attendance' },
  { key: 'settings.view', label: 'View settings' }
]
